[build]
  # Le build se fait dans le dossier mon-projet-vite
  base = "mon-projet-vite"
  publish = "dist"
  command = "npm ci && npm run build"

[build.environment]
  # Runtime Node et NPM pour Netlify
  NODE_VERSION = "20.19.0"
  NPM_VERSION  = "10.8.2"

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173
  autoLaunch = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuration Netlify optimisée pour MyConfort SPA

# ✅ Sécurité basique côté CDN
[[headers]]
for = "/*"
  [headers.values]
  Cache-Control = "no-cache, no-store, must-revalidate"
  Pragma = "no-cache"
  Expires = "0"
  X-Frame-Options = "DENY"
  X-Content-Type-Options = "nosniff"
  X-XSS-Protection = "1; mode=block"
  Referrer-Policy = "strict-origin-when-cross-origin"

# ✅ Cache fort sur les assets fingerprintés
[[headers]]
for = "/assets/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

# ✅ Images: cache long mais modifiable
[[headers]]
for = "/images/*"
  [headers.values]
  Cache-Control = "public, max-age=604800"
