# netlify.toml
# Configuration Netlify optimisée pour MyConfort SPA
[build]
  command = "cd mon-projet-vite && npm ci && npm run build"
  publish = "mon-projet-vite/dist"

[build.environment]
  NODE_VERSION = "20.11.1"
  NPM_FLAGS = "--no-audit --no-fund"
  
# Redirects SPA - IMPORTANT pour éviter les 404
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Headers pour performance et sécurité
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"
