[build]
  base    = "mon-projet-vite"   # CE dossier doit exister dans le repo
  publish = "public"            # on met un placeholder (étape 2)
  command = ":"                 # no-op: on déploie surtout les Functions

[functions]
  directory = "netlify/functions"   # chemin RELATIF à la base ci-dessus
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs"]

[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200
  force = true

# Catch-all SPA / page racine (à garder EN DERNIER)
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
