[build]
  base = "mon-projet-vite"
  publish = "mon-projet-vite/dist"
  command = "npm ci && npm run build"

  [build.environment]
    NODE_VERSION = "20"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuration Netlify optimisée pour MyConfort SPA

[build]
  # Le build se fait dans le dossier mon-projet-vite
  base = "mon-projet-vite"
  publish = "dist"
  command = "npm ci && npm run build"

[build.environment]
  # Force le runtime compatible avec ton projet
  NODE_VERSION = "20.18.0"
  NPM_VERSION  = "10.8.2"

# ✅ Sécurité basique côté CDN
[[headers]]
for = "/*"
  [headers.values]
  X-Frame-Options = "DENY"
  X-Content-Type-Options = "nosniff"
  X-XSS-Protection = "1; mode=block"
  Referrer-Policy = "strict-origin-when-cross-origin"

# ✅ Cache fort sur les assets fingerprintés
[[headers]]
for = "/assets/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"
