# netlify.toml
# Configuration Netlify optimisée pour MyConfort SPA
[build]
  # Netlify exécutera la commande depuis ce dossier
  base = "mon-projet-vite"
  publish = "dist"
  command = "npm run build"

[build.environment]
  # Force le runtime compatible avec ton projet
  NODE_VERSION = "20.18.0"
  NPM_VERSION = "10.8.2"
  
# Redirects SPA - IMPORTANT pour éviter les 404
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# ✅ Sécurité basique côté CDN
[[headers]]
for = "/*"
  [headers.values]
  X-Frame-Options = "DENY"
  X-Content-Type-Options = "nosniff"
  X-XSS-Protection = "1; mode=block"
  Referrer-Policy = "strict-origin-when-cross-origin"

# ✅ Cache fort sur les assets fingerprintés
[[headers]]
for = "/assets/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"
