[build]
  base    = "mon-projet-vite"   # CE dossier doit exister dans le repo
  publish = "dist"              # Application React buildée
  command = "npm install && npm run build"  # Build complet

[functions]
  directory = "netlify/functions"   # chemin RELATIF à la base ci-dessus
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs"]

[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200
  force = true

# Catch-all SPA / page racine (à garder EN DERNIER)
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
