[build]
  publish = "mon-projet-vite/dist"
  command = "cd mon-projet-vite && npm install && npm run build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/n8n/*"
  to = "/.netlify/functions/n8n-proxy/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
