[build]
  publish = "mon-projet-vite/dist"
  command = "cd mon-projet-vite && npm install && npm run build:netlify"

[functions]
  directory = "netlify/functions"

# Redirects spécifiques (doivent être AVANT les wildcards)
[[redirects]]
  from = "/api/n8n/webhook/caisse/factures"
  to = "/.netlify/functions/caisse-factures"
  status = 200

[[redirects]]
  from = "/api/caisse/facture"
  to = "/.netlify/functions/caisse-facture"
  status = 200

# Redirect wildcard (doit être APRÈS les spécifiques)
[[redirects]]
  from = "/api/n8n/*"
  to = "/.netlify/functions/n8n-proxy/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
