[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  # Variables de versioning automatiques
  VITE_COMMIT_REF = "${COMMIT_REF}"
  VITE_BRANCH = "${BRANCH}"
  VITE_CONTEXT = "${CONTEXT}"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
